// Generated by scripts/extract-strings.mjs from design/*.dc.html.
// Values are copied byte-for-byte out of the design export, then passed through
// scripts/i18n-transforms.mjs for the client's copy edits. Do not edit by hand,
// do not re-type Devanagari, and do not translate a missing string — re-run the script.

export const en = {
  "About": {
    "S": {
      "kicker": "About us",
      "title": "Shri Krishna Pathey Nyas",
      "lede": "Shri Krishna Pathey Nyas was established by the Department of Culture, Government of Madhya Pradesh, to research the various places along the journey undertaken by Yugavatar Bhagwan Shri Krishna — guide to Bharatvarsh and the world for the nation’s renewal and ascent — with Ujjain, Madhya Pradesh at its centre, to develop them as places of pilgrimage, and to protect and promote the literature and culture of the regions concerned.",
      "illoAlt": "Symbolic illustration of a luminous cosmos",
      "objectsTitle": "Objects of the trust",
      "objects": [
        "Identify, develop, protect and preserve the places in Madhya Pradesh associated with the travels of Bhagwan Shri Krishna, and document them through recording, photography, filming and illustration.",
        "Protect and manage the temples, water structures, forest wealth and gardens within those sites, and promote them nationally and internationally.",
        "Establish a Sandipani Gurukul at Ujjain for formal instruction in the 14 Vidyas and 64 Kalas.",
        "Build and manage auditoria, community centres and dharmshalas.",
        "Develop the heritage of education, culture, agriculture, and cow and livestock husbandry.",
        "Connect the younger generation, emotionally and experientially, to the story of Bhagwan Shri Krishna and the destinations of his journeys.",
        "Establish libraries, museums and information centres for tourists, researchers, youth and students.",
        "Document the contribution of the sages, saints, thinkers, poets, writers, artists and scientists who helped establish Shri Krishna as Jagadguru."
      ],
      "sandipaniTitle": "Guru Sandipani and Shri Krishna",
      "sandipaniP1": "The personality of Bhagwan Shri Krishna was completed not by his leelas and valour alone, but by the education, character and discipline he received at the ashram of Maharishi Sandipani. There, through the 14 Vidyas, the 64 Kalas and the Indian knowledge tradition, he learned discernment, service, patience, duty and leadership. That guru–shishya parampara became the greatest strength of his life and later established him as Jagadguru.",
      "sandipaniP2": "Founded on that ideal, the Bhagwan Shri Krishna Medhavi Chhatravritti Pratiyogita encourages students to study the 14 Vidyas, the 64 Kalas and the Indian knowledge tradition, and so strengthens the nation-building values that rest on knowledge, culture and character.",
      "emailLabel": "Official email",
      "officeLabel": "Office",
      "officeValue": "Shri Krishna Pathey Nyas, Pratham Tal, Ravindra Bhawan Sabhagam, Polytechnic Chauraha, Bhopal, Madhya Pradesh - 462003",
      "phoneLabel": "Phone",
      "phoneValue": "0755 4535064",
      "writeToUs": "Write an email"
    },
    "markup": {
      "text0": "shrikrishnapatheynyas@gmail.com"
    }
  },
  "Certificates": {
    "S": {
      "title": "Certificate",
      "certAlt": "Participation certificate",
      "download": "Download certificate"
    }
  },
  "CtaBox": {
    "T": {
      "out": [
        "Enter the competition",
        "Registration takes only a few minutes.",
        "Register now"
      ],
      "pending": [
        "You have not taken part in the competition yet",
        "Begin now.",
        "Take part"
      ],
      "done": [
        "Thank you for taking part in the competition",
        "View your certificate.",
        "View certificate"
      ]
    }
  },
  "Home_v5": {
    "VIDYAS": [
      [
        "ऋग्वेद",
        "चार वेद",
        "Rigveda",
        "The first of the four Vedas",
        "ऋग्वेद"
      ],
      [
        "यजुर्वेद",
        "चार वेद",
        "Yajurveda",
        "Mantras and method of yajna",
        "यजुर्वेद"
      ],
      [
        "सामवेद",
        "चार वेद",
        "Samaveda",
        "The tradition of chant and music",
        "सामवेद"
      ],
      [
        "अथर्ववेद",
        "चार वेद",
        "Atharvaveda",
        "Everyday life, medicine and science",
        "अथर्ववेद"
      ],
      [
        "शिक्षा",
        "उच्चारण विज्ञान",
        "Shiksha",
        "Phonetics and articulation",
        "शिक्षा"
      ],
      [
        "छंद",
        "छह वेदांग",
        "Chhanda",
        "Prosody and metre",
        "छंद"
      ],
      [
        "व्याकरण",
        "छह वेदांग",
        "Vyakarana",
        "Grammar",
        "व्याकरण शास्त्र"
      ],
      [
        "निरुक्त",
        "शब्द व्युत्पत्ति",
        "Nirukta",
        "Etymology",
        "निरुक्त"
      ],
      [
        "ज्योतिष",
        "छह वेदांग",
        "Jyotisha",
        "Astronomy and time-reckoning",
        "ज्योतिष"
      ],
      [
        "धर्म शास्त्र",
        "कानून/नीति",
        "Dharmashastra",
        "Law, ethics and conduct",
        "धर्म शास्त्र"
      ],
      [
        "कल्प",
        "कर्मकांड",
        "Kalpa",
        "Ritual and procedure",
        "कल्प"
      ],
      [
        "पुराण",
        "अन्य चार",
        "Purana",
        "History and narrative tradition",
        "पुराण"
      ],
      [
        "मीमांसा",
        "दर्शन",
        "Mimamsa",
        "Philosophy of interpretation",
        "मीमांसा"
      ],
      [
        "न्याय",
        "तर्कशास्त्र",
        "Nyaya",
        "Logic and reasoning",
        "न्याय विद्या"
      ]
    ],
    "KALAS": [
      [
        "गीत",
        "गायन",
        "Geet",
        "Singing",
        "गीत"
      ],
      [
        "वाद्य",
        "वाद्ययंत्र बजाना",
        "Vadya",
        "Playing instruments",
        "वाद्य"
      ],
      [
        "नृत्य",
        "अभिनय",
        "Nritya",
        "Acting",
        "नृत्य / नृत्त कला"
      ],
      [
        "आलेख्य",
        "चित्रकला",
        "Alekhya",
        "Painting",
        "आलेख्य"
      ],
      [
        "विशेषकच्छेद्य",
        "तिलक व शारीरिक सजावट",
        "Visheshakachchhedya",
        "Forehead marks and body adornment",
        "विशेषकच्छेद्य"
      ],
      [
        "तंडुलकुसुम वलिविकार",
        "चावल और फूलों से आकृतियां बनाना",
        "Tandula-kusuma",
        "Rangoli with rice and flowers",
        "तंडुलकुसुम वलिविकार"
      ],
      [
        "पुष्पास्तरण",
        "फूलों की सेज सजाना",
        "Pushpastarana",
        "Arranging flower beds",
        "पुष्पास्तरण"
      ],
      [
        "दशनवसनांगराग",
        "वस्त्र और अंगों को रंगना/सजाना",
        "Dashana-vasana-raga",
        "Colouring teeth, cloth and limbs",
        "दशनवसनांगराग कला"
      ],
      [
        "मणिभूमिका कर्म",
        "जवाहरात जड़ना",
        "Manibhumika-karma",
        "Setting jewels",
        "मणिभूमिका कर्म"
      ],
      [
        "शयन रचना",
        "बिस्तर सजाना",
        "Shayana-rachana",
        "Preparing a bed chamber",
        "शयन रचना"
      ],
      [
        "उदक वाद्य",
        "जल तरंग बजाना",
        "Udaka-vadya",
        "Music on water",
        "उदक वाद्य"
      ],
      [
        "उदकाघात",
        "पानी से खेलना/छपछपाना",
        "Udaka-ghata",
        "Water sport",
        "उदकाघात"
      ],
      [
        "चित्राश्चयोग",
        "रंगों का मिश्रण",
        "Chitra-yoga",
        "Mixing colours",
        "चित्राश्चयोग"
      ],
      [
        "माल्यग्रंथन",
        "माला गूंथना",
        "Malya-grathana",
        "Weaving garlands",
        "माल्यग्रंथन"
      ],
      [
        "शेखर कापीडयोजन",
        "सिर पर मुकुट या फूल सजाना",
        "Shekharaka-yojana",
        "Crowns and head ornaments",
        "शेखर कापीडयोजन"
      ],
      [
        "नेपथ्य प्रयोग",
        "वेशभूषा धारण करना",
        "Nepathya-yoga",
        "Costume and stagecraft",
        "नेपथ्य प्रयोग"
      ],
      [
        "कर्णपत्र भंग",
        "कान के आभूषण बनाना",
        "Karnapatra-bhanga",
        "Making ear ornaments",
        "कर्णपत्र भंग"
      ],
      [
        "गन्धायुक्ति",
        "इत्र और सुगंधित पदार्थ बनाना",
        "Gandha-yukti",
        "Making perfume",
        "गन्धायुक्ति"
      ],
      [
        "भूषण योजन",
        "गहने पहनना",
        "Bhushana-yojana",
        "The art of adornment",
        "भूषण योजन"
      ],
      [
        "ऐन्द्रजाल",
        "जादू-गरी",
        "Aindrajala",
        "Conjuring",
        "ऐन्द्रजाल"
      ],
      [
        "कौचुमार",
        "छद्म वेश या रूप बदलना",
        "Kauchumara-yoga",
        "Changing one's appearance",
        "कौचुमार"
      ],
      [
        "हस्तलाघव",
        "हाथ की सफाई",
        "Hasta-laghava",
        "Manual dexterity",
        "हस्तलाघव"
      ],
      [
        "विचित्रशाकयूषभक्ष्य विकार क्रिया",
        "स्वादिष्ट व्यंजन बनाना",
        "Vichitra-bhakshya",
        "Cooking varied dishes",
        "विचित्रशाकयूषभक्ष्य विकार क्रिया"
      ],
      [
        "पानकरस-रागासव योजन",
        "पेय पदार्थ और शर्बत बनाना",
        "Panaka-rasa-yojana",
        "Preparing drinks and syrups",
        "पानकरस-रागासव योजन"
      ],
      [
        "सूचीवान कर्म",
        "सिलाई और बुनाई",
        "Suchi-vana-karma",
        "Sewing and weaving",
        "सूचीवान कर्म"
      ],
      [
        "सूत्रक्रीड़ा",
        "धागों का खेल",
        "Sutra-krida",
        "Games with threads",
        "सूत्रक्रीड़ा"
      ],
      [
        "वीणाडमरूकवाद्यानि",
        "वीणा और डमरू बजाना",
        "Vina-damaruka",
        "Playing vina and damaru",
        "वीणाडमरूकवाद्यानि"
      ],
      [
        "प्रहेलिका",
        "पहेलियां बुझाना",
        "Prahelika",
        "Composing riddles",
        "प्रहेलिका"
      ],
      [
        "प्रतिमाला",
        "श्लोक या तुकबंदी बनाना",
        "Pratimala",
        "Verse-capping games",
        "प्रतिमाला"
      ],
      [
        "दुर्वाचक योग",
        "कठिन शब्दों के अर्थ समझना",
        "Durvachaka-yoga",
        "Understanding difficult words",
        "दुर्वाचक योग"
      ],
      [
        "पुस्तकवाचन",
        "ग्रंथों का वाचन",
        "Pustaka-vachana",
        "Reading aloud",
        "पुस्तकवाचन"
      ],
      [
        "नाटकाख्यायिका दर्शन",
        "नाटक और कहानियों की रचना",
        "Natika-akhyayika",
        "Knowledge of plays and tales",
        "नाटकाख्यायिका दर्शन"
      ],
      [
        "काव्यसमस्यापूरण",
        "अधूरी कविता को पूरा करना",
        "Kavya-samasya-purana",
        "Completing verses",
        "काव्यसमस्यापूरण"
      ],
      [
        "पट्टिकावेत्रवान विकल्प",
        "चटाई और टोकरी बुनना",
        "Pattika-vetra-vana",
        "Weaving mats and baskets",
        "पट्टिकावेत्रवान विकल्प"
      ],
      [
        "तक्षकर्म",
        null,
        "Takshakarma",
        null,
        "तक्षकर्म"
      ],
      [
        "तक्षण",
        "बढ़ईगिरी / लकड़ी का काम",
        "Takshana",
        "Carpentry",
        "तक्षण कला"
      ],
      [
        "वास्तुविद्या",
        "भवन निर्माण और वास्तुकला",
        "Vastu-vidya",
        "Architecture",
        "वास्तुविद्या"
      ],
      [
        "रूप्यरत्न परीक्षा",
        "चांदी और रत्नों की पहचान",
        "Rupya-ratna-pariksha",
        "Assaying gems and metals",
        "रूप्यरत्न परीक्षा"
      ],
      [
        "धातुवाद",
        "धातुओं को पिघलाना / धातु विज्ञान",
        "Dhatu-vada",
        "Metallurgy",
        "धातुवाद"
      ],
      [
        "मणिरागाकर ज्ञान",
        "रत्नों के रंग की पहचान",
        "Mani-raga-jnana",
        "Colouring gems",
        "मणिरागाकर ज्ञान"
      ],
      [
        "वृक्षायुर्वेद योग",
        "पेड़-पौधों की चिकित्सा",
        "Vrikshayurveda",
        "Medicine for trees",
        "वृक्षायुर्वेद योग"
      ],
      [
        "मेषकुक्कुट लावकयुद्ध विधि",
        "पशु-पक्षियों के युद्ध का ज्ञान",
        "Mesha-kukkuta-vidhi",
        "Training animals to contest",
        "मेषकुक्कुट लावकयुद्ध विधि"
      ],
      [
        "शुक-सारिका प्रलापन",
        "तोता-मैना को बोलना सिखाना",
        "Shuka-sarika-pralapana",
        "Teaching birds to speak",
        "शुक-सारिका प्रलापन"
      ],
      [
        "उत्सादन-संवाहन-केशमर्दन कुशलता",
        "मालिश करना",
        "Utsadana",
        "Massage and body care",
        "उत्सादन-संवाहन-केशमर्दन कुशलता"
      ],
      [
        "अक्षरमुष्टि कथन",
        "इशारों में बात करना",
        "Akshara-mushtika",
        "Sign language",
        "अक्षरमुष्टि कथन"
      ],
      [
        "म्लेच्छित विकल्प",
        "विदेशी भाषाएं सीखना",
        "Mlechchhita-kala",
        "Learning foreign languages",
        "म्लेच्छित विकल्प"
      ],
      [
        "देशभाषा विज्ञान",
        "क्षेत्रीय बोलियों का ज्ञान",
        "Desha-bhasha-jnana",
        "Knowledge of regional languages",
        "देशभाषा विज्ञान"
      ],
      [
        "पुष्पशकटिका",
        null,
        "Pushpa-shakatika",
        null,
        "पुष्पशकटिका"
      ],
      [
        "निमित्त ज्ञान",
        "शकुन-अपशकुन का ज्ञान",
        "Nimitta-jnana",
        null,
        "निमित्त ज्ञान"
      ],
      [
        "यन्त्रमातृका",
        "मशीनों का संचालन",
        "Yantra-matrika",
        "Building and running machines",
        "यन्त्रमातृका"
      ],
      [
        "धारणमातृका",
        "स्मरण शक्ति बढ़ाना",
        "Dharana-matrika",
        "Strengthening memory",
        "धारणमातृका"
      ],
      [
        "सम्पाठ्यम्",
        "साथ मिलकर पढ़ना",
        "Sampathya",
        "Reciting in unison",
        "सम्पाठ्यम्"
      ],
      [
        "मानसी",
        "मन में कविता रचना",
        "Manasi-kavya-kriya",
        "Extempore poetry",
        "मानसी"
      ],
      [
        "अभिधानकोष",
        "शब्दकोश",
        "Abhidhana-kosha",
        "Lexicon and metre",
        "अभिधानकोष"
      ],
      [
        "छन्दोज्ञान",
        "छंदों का ज्ञान",
        "Chhando-jnana",
        null,
        "छन्दोज्ञान"
      ],
      [
        "क्रियाकल्प",
        "दूसरों का काम पूरा करना",
        "Kriya-vikalpa",
        "Completing another's work",
        "क्रियाकल्प"
      ],
      [
        "छलितयोग",
        "छल-कपट का ज्ञान",
        "Chhalitaka-yoga",
        "Knowledge of deception",
        "छलितयोग"
      ],
      [
        "वस्त्रगोपन",
        "वस्त्र छिपाना",
        "Vastra-gopana",
        "Concealing garments",
        "वस्त्रगोपन"
      ],
      [
        "द्यूतविशेष",
        "शतरंज का ज्ञान",
        "Dyuta-vishesha",
        "Knowledge of chess",
        "द्यूतविशेष"
      ],
      [
        "आकर्षक्रीड़ा",
        "चुंबक का खेल",
        "Akarsha-krida",
        "Play with magnets",
        "आकर्षक्रीड़ा"
      ],
      [
        "बालक्रीड़नक",
        "बच्चों के खेल",
        "Balakridanaka",
        "Games for children",
        "बालक्रीड़नक"
      ],
      [
        "वैनायिकी विद्या",
        "विनय और अनुशासन",
        "Vainayiki-vidya",
        "Discipline and etiquette",
        "वैनायिकी विद्या"
      ],
      [
        "वैजयिकी विद्या",
        "विजय प्राप्त करने की कला",
        "Vaijayiki-vidya",
        "The art of victory",
        "वैजयिकी विद्या"
      ],
      [
        "व्यायामिकी",
        null,
        "Vyayamiki",
        null,
        "व्यायामिकी"
      ]
    ],
    "S": {
      "org": "Shri Krishna Pathey Nyas, Bhopal",
      "heroTitle": "Bhagwan Shri Krishna Medhavi Chhatravritti Yojana",
      "heroDate": "10 August 2026",
      "heroLede": "A free competition on the 14 Vidyas, the 64 Kalas and the Indian knowledge tradition.",
      "ctaPrimaryOut": "Register now",
      "ctaTake": "Take part",
      "ctaCert": "View certificate",
      "ctaSecondary": "Read the rules",
      "facts": [
        {
          "value": "₹1,00,000",
          "label": "Scholarship"
        },
        {
          "value": "102",
          "label": "Scholarships"
        },
        {
          "value": "30",
          "label": "Questions"
        },
        {
          "value": "10",
          "label": "Minutes"
        }
      ],
      "sylKicker": "Competition",
      "sylTitle": "Guru Sandipani and Shri Krishna",
      "sylLede": "The personality of Bhagwan Shri Krishna was completed not by his leelas and valour alone, but by the education, character and discipline he received at the ashram of Maharishi Sandipani. There, through the 14 Vidyas, the 64 Kalas and the Indian knowledge tradition, he learned discernment, service, patience, duty and leadership. That guru–shishya parampara became the greatest strength of his life and later established him as Jagadguru.",
      "tabVidyas": "14 Vidyas",
      "tabKalas": "64 Kalas",
      "prevLabel": "Previous card",
      "nextLabel": "Next card",
      "howTitle": "How it works",
      "steps": [
        {
          "title": "Register"
        },
        {
          "title": "Read the rules"
        },
        {
          "title": "Take the quiz"
        },
        {
          "title": "Certificate"
        }
      ],
      "datesTitle": "Competition start, results and distribution dates",
      "dateSteps": [
        "1",
        "2",
        "3"
      ],
      "dates": [
        {
          "when": "10 August 2026",
          "what": "Competition opens",
          "note": "Competition opens"
        },
        {
          "when": "30 September 2026",
          "what": "Last date for entries",
          "note": "Last date for entries"
        },
        {
          "when": "1 November 2026",
          "what": "Madhya Pradesh Sthapana Diwas",
          "note": "Scholarship distribution"
        }
      ],
      "closeTitle": "Enter the competition",
      "closeBody": "Registration takes a few minutes.",
      "heroDateRange": "10 August 2026 to 30 September 2026",
      "factTimeValue": "10 minutes",
      "factTimeLabel": "time"
    },
    "markup": {
      "alt0": "Shri Krishna Pathey Nyas"
    },
    "inline": [
      "Vidya ",
      "Kala "
    ]
  },
  "Leadership": {
    "LEADERS": [
      [
        "Chairperson",
        "Dr. Mohan Yadav",
        "Hon'ble Chief Minister, Madhya Pradesh"
      ],
      [
        "Trustee Secretary",
        "Shri Sheo Shekhar Shukla",
        "Additional Chief Secretary, Culture"
      ],
      [
        "Vice-Chairperson",
        "Shri Dharmendra Bhav Singh Lodhi",
        "Hon'ble Minister of State for Culture (Independent Charge)"
      ],
      [
        "Chief Executive Officer",
        "Shri Shriram Tiwari",
        "Cultural Adviser to the Hon'ble Chief Minister"
      ]
    ],
    "markup": {
      "text0": "श्रीकृष्ण पाथेय न्यास"
    },
    "inline": [
      "Previous card",
      "Next card"
    ]
  },
  "Legal": {
    "S": {
      "privacyTab": "Privacy notice",
      "termsTab": "Terms of use",
      "questions": "If you have a question,",
      "contactLink": "contact us",
      "privacy": {
        "title": "Privacy notice",
        "lede": "What we collect, why we collect it and who can see it.",
        "sections": [
          {
            "title": "What we collect",
            "points": [
              "Your mobile number, which is your identity here.",
              "Name, email, date of birth, gender and address.",
              "Category, Educational qualification and name of institution.",
              "Your answers, score and time taken in the competition."
            ]
          },
          {
            "title": "Why we use it",
            "points": [
              "To run the competition, prepare merit lists and publish results.",
              "To carry out the scholarship process and contact you if you are selected.",
              "For nothing else. We do not sell your information and we do not show advertising."
            ]
          },
          {
            "title": "Who can see it",
            "points": [
              "Authorised staff of the Nyas and the Department of Culture, and the selection committee.",
              "Names, districts and institutions of selected students may appear in published results."
            ]
          },
          {
            "title": "Your rights",
            "points": [
              "You may ask what information about you we hold.",
              "For a genuine correction or a grievance, write to shrikrishnapatheynyas@gmail.com."
            ]
          }
        ]
      },
      "terms": {
        "title": "Terms of use",
        "lede": "These terms apply when you use this website.",
        "sections": [
          {
            "title": "Purpose",
            "points": [
              "This website is operated by Shri Krishna Pathey Nyas, Bhopal.",
              "Its purpose is to publish information about the Nyas and to run the Bhagwan Shri Krishna Medhavi Chhatravritti Pratiyogita."
            ]
          },
          {
            "title": "Your responsibility",
            "points": [
              "Give correct information at registration. False information cancels the entry.",
              "Register once and take the competition only once.",
              "Do not take help from another person or use any unfair method during the quiz."
            ]
          },
          {
            "title": "Content",
            "points": [
              "The content, marks and images on this website belong to the Nyas or the relevant authorities.",
              "Do not use them commercially without permission."
            ]
          },
          {
            "title": "Changes and decisions",
            "points": [
              "Rules and dates may change, and changes will be published on this website.",
              "In all matters concerning the competition and selection, the decision of the Nyas is final. Jurisdiction is Bhopal.",
              "The Hindi version is authoritative; the English translation is a courtesy."
            ]
          }
        ]
      }
    }
  },
  "Login": {
    "S": {
      "title": "Sign in",
      "lede": "Enter the same mobile number you registered with.",
      "asideOrg": "Shri Krishna Pathey Nyas, Bhopal",
      "asideKicker": "10 August 2026",
      "asideTitle": "Bhagwan Shri Krishna Medhavi Chhatravritti Pratiyogita",
      "slides": [
        {
          "value": "₹1,00,000",
          "label": "Scholarship"
        },
        {
          "value": "102",
          "label": "Winners sponsored"
        },
        {
          "value": "30",
          "label": "Questions"
        },
        {
          "value": "10",
          "label": "Minutes"
        }
      ],
      "mobileLabel": "Mobile number",
      "mobileInvalid": "Enter a 10-digit number starting with 6, 7, 8 or 9",
      "continue": "Sign in",
      "noAccount": "No account yet?",
      "register": "Register"
    },
    "markup": {
      "placeholder0": "00000 00000",
      "text0": "+91"
    }
  },
  "Pratiyogita": {
    "S": {
      "kicker": "The competition",
      "title": "Bhagwan Shri Krishna Medhavi Chhatravritti Pratiyogita",
      "lede": "A free competition for students of Madhya Pradesh on the 14 Vidyas, the 64 Kalas, Maharishi Sandipani and the Indian knowledge tradition.",
      "ctaPrimary": "Register now",
      "ctaTake": "Take part",
      "ctaAgain": "View certificate",
      "ctaSecondary": "Read the rules",
      "prizeLine": "A scholarship of one lakh rupees each for 102 selected winners.",
      "whoTitle": "Who can participate",
      "categories": [
        {
          "name": "Vidyalaya Star",
          "who": "Students of Classes 9 to 12",
          "count": "51 scholarships",
          "kind": "school"
        },
        {
          "name": "Mahavidyalaya Star",
          "who": "Students of colleges, universities, polytechnics or ITIs",
          "count": "51 scholarships",
          "kind": "college"
        }
      ],
      "examEyebrow": "Entrance-exam candidates",
      "examTitle": "Entrance-exam aspirants are just as welcome to take part.",
      "formatTitle": "Format",
      "format": [
        {
          "value": "30",
          "label": "Questions, one correct option each"
        },
        {
          "value": "10 minutes",
          "label": "Total time, auto-submits when time expires"
        }
      ],
      "datesTitle": "Dates",
      "dates": [
        {
          "when": "10 August 2026",
          "what": "Competition opens",
          "note": "Competition opens"
        },
        {
          "when": "30 September 2026",
          "what": "Last date for entries",
          "note": "Last date for entries"
        },
        {
          "when": "1 November 2026",
          "what": "Madhya Pradesh Sthapana Diwas",
          "note": "Scholarship distribution"
        }
      ],
      "closeTitle": "Enter the competition",
      "formatFirstValue": "30 Questions",
      "formatFirstLabel": "one correct option each"
    },
    "EXAM_ROW_A": [
      "NEET UG",
      "JEE Main",
      "JEE Advanced",
      "CUET",
      "BITSAT",
      "GATE",
      "CAT",
      "XAT",
      "CLAT",
      "AILET",
      "NDA",
      "CDS",
      "AFCAT"
    ],
    "EXAM_ROW_B": [
      "UPSC CSE",
      "MPPSC",
      "SSC CGL",
      "IBPS PO",
      "UGC NET",
      "CA",
      "CS",
      "CMA",
      "NIFT",
      "NID",
      "NTSE",
      "MP PAT",
      "MP PET"
    ]
  },
  "Profile": {
    "S": {
      "lockNote": "Details cannot be changed after registration. For a genuine correction, write to",
      "participation": "Participation",
      "stats": [
        "Date of attempt",
        "Time taken"
      ],
      "status": "Competition completed",
      "viewCertificate": "Certificate",
      "bestNote": "Each student may take the competition only once.",
      "groups": [
        "Personal details",
        "Sign in",
        "Address",
        "Education"
      ],
      "keys": {
        "name": "Name",
        "gender": "Gender",
        "dob": "Date of birth",
        "mobile": "Mobile number",
        "email": "Email",
        "provider": "Sign-in method",
        "address": "Address",
        "city": "City or village",
        "district": "District",
        "state": "State",
        "pin": "PIN code",
        "category": "Category",
        "level": "Educational qualification",
        "institution": "Institution",
        "exam": "Competitive exam",
        "divyang": "Divyang category"
      },
      "mobileNote": "This is the mobile number used to sign in.",
      "mobileSignIn": "With a mobile number",
      "otpLabel": "With an email code",
      "divyangNo": "No",
      "divyangYes": "Yes",
      "divyangNote": "If selected under the divyang category, a government-issued disability certificate must be produced.",
      "stateValue": "Madhya Pradesh",
      "categories": {
        "vidyalaya": "Vidyalaya Star",
        "mahavidyalaya": "Mahavidyalaya Star"
      },
      "langTitle": "Language",
      "langNote": "This is the only editable setting on this page.",
      "startQuiz": "Start the quiz",
      "signOut": "Sign out"
    },
    "markup": {
      "text0": "·",
      "text1": "shrikrishnapatheynyas@gmail.com",
      "text2": "→",
      "text3": "हिन्दी",
      "text4": "English"
    },
    "inline": [
      "No",
      "No",
      "time ",
      "Completed"
    ]
  },
  "Quiz": {
    "T": {
      "insTitle": "Before you begin",
      "insLede": "Please read these points carefully. The timer starts the moment you press Begin.",
      "instructions": [
        "30 questions. One correct option per question.",
        "10 minutes in total.",
        "There is no negative marking.",
        "The examination ends when the time is over.",
        "Once submitted, answers in that attempt cannot be changed.",
        "Each student may take the competition only once."
      ],
      "insWarning": "The timer will not be extended for a lost connection or any other interruption. Your answers are saved as you go.",
      "begin": "Begin",
      "exit": "Leave",
      "timeLeft": "Time remaining",
      "normal": "left",
      "warning": "Careful",
      "critical": "Final moments",
      "offline": "The connection has dropped. Your answers are saved and it will reconnect on its own.",
      "questionOf": "Question",
      "of": "of",
      "prev": "Previous",
      "guardMsg": "Please select an option before moving to another question.",
      "nextLabel": "Next",
      "clear": "Clear response",
      "submit": "Submit",
      "paletteTitle": "Question list",
      "close": "Close",
      "states": [
        "Current",
        "Answered",
        "Visited, unanswered",
        "Not visited"
      ],
      "confirmTitle": "Submit this attempt?",
      "summary": [
        "Answered",
        "Not answered",
        "Time remaining"
      ],
      "confirmWarn1": "Once submitted this attempt is final.",
      "confirmWarn2": "A second attempt is not possible.",
      "goBack": "Go back",
      "confirm": "Yes, submit",
      "doneTitle": "Your attempt has been recorded",
      "submittedManual": "Submitted",
      "submittedAuto": "Time expired, submitted automatically",
      "stamp": "Recorded at",
      "results": [
        "Answered",
        "Not answered",
        "Attempts taken",
        "Time taken"
      ],
      "resultsNote": "Results will be published on this website and selected students will be informed by email and mobile. On 1 November 2026 the scholarship will be presented to the selected students.",
      "download": "Certificate",
      "home": "Home",
      "onceTitle": "Your attempt is already recorded",
      "onceBody": "Each student may take the competition only once. Your attempt has been recorded, so a second attempt is not possible.",
      "profile": "My account",
      "ann5": "5 minutes remaining",
      "ann2": "2 minutes remaining",
      "ann1": "1 minute remaining",
      "ann30": "30 seconds remaining"
    },
    "markup": {
      "alt0": "Shri Krishna Pathey Nyas",
      "ariaLabel0": "Switch language",
      "text0": "हिं",
      "text1": "EN",
      "text2": "!",
      "text3": "×",
      "text4": "!"
    },
    "inline": [
      "A",
      "B",
      "C",
      "D",
      "जनवरी",
      "फरवरी",
      "मार्च",
      "अप्रैल",
      "मई",
      "जून",
      "जुलाई",
      "अगस्त",
      "सितम्बर",
      "अक्टूबर",
      "नवंबर",
      "दिसंबर"
    ]
  },
  "Register": {
    "DISTRICTS": [
      [
        "Agar Malwa",
        "आगर मालवा"
      ],
      [
        "Alirajpur",
        "अलीराजपुर"
      ],
      [
        "Anuppur",
        "अनूपपुर"
      ],
      [
        "Ashoknagar",
        "अशोकनगर"
      ],
      [
        "Balaghat",
        "बालाघाट"
      ],
      [
        "Barwani",
        "बड़वानी"
      ],
      [
        "Betul",
        "बैतूल"
      ],
      [
        "Bhind",
        "भिंड"
      ],
      [
        "Bhopal",
        "भोपाल"
      ],
      [
        "Burhanpur",
        "बुरहानपुर"
      ],
      [
        "Chhatarpur",
        "छतरपुर"
      ],
      [
        "Chhindwara",
        "छिंदवाड़ा"
      ],
      [
        "Damoh",
        "दमोह"
      ],
      [
        "Datia",
        "दतिया"
      ],
      [
        "Dewas",
        "देवास"
      ],
      [
        "Dhar",
        "धार"
      ],
      [
        "Dindori",
        "डिंडौरी"
      ],
      [
        "Guna",
        "गुना"
      ],
      [
        "Gwalior",
        "ग्वालियर"
      ],
      [
        "Harda",
        "हरदा"
      ],
      [
        "Indore",
        "इंदौर"
      ],
      [
        "Jabalpur",
        "जबलपुर"
      ],
      [
        "Jhabua",
        "झाबुआ"
      ],
      [
        "Katni",
        "कटनी"
      ],
      [
        "Khandwa",
        "खंडवा"
      ],
      [
        "Khargone",
        "खरगोन"
      ],
      [
        "Maihar",
        "मैहर"
      ],
      [
        "Mandla",
        "मंडला"
      ],
      [
        "Mandsaur",
        "मंदसौर"
      ],
      [
        "Mauganj",
        "मऊगंज"
      ],
      [
        "Morena",
        "मुरैना"
      ],
      [
        "Narmadapuram",
        "नर्मदापुरम"
      ],
      [
        "Narsinghpur",
        "नरसिंहपुर"
      ],
      [
        "Neemuch",
        "नीमच"
      ],
      [
        "Niwari",
        "निवाड़ी"
      ],
      [
        "Pandhurna",
        "पांढुर्णा"
      ],
      [
        "Panna",
        "पन्ना"
      ],
      [
        "Raisen",
        "रायसेन"
      ],
      [
        "Rajgarh",
        "राजगढ़"
      ],
      [
        "Ratlam",
        "रतलाम"
      ],
      [
        "Rewa",
        "रीवा"
      ],
      [
        "Sagar",
        "सागर"
      ],
      [
        "Satna",
        "सतना"
      ],
      [
        "Sehore",
        "सीहोर"
      ],
      [
        "Seoni",
        "सिवनी"
      ],
      [
        "Shahdol",
        "शहडोल"
      ],
      [
        "Shajapur",
        "शाजापुर"
      ],
      [
        "Sheopur",
        "श्योपुर"
      ],
      [
        "Shivpuri",
        "शिवपुरी"
      ],
      [
        "Sidhi",
        "सीधी"
      ],
      [
        "Singrauli",
        "सिंगरौली"
      ],
      [
        "Tikamgarh",
        "टीकमगढ़"
      ],
      [
        "Ujjain",
        "उज्जैन"
      ],
      [
        "Umaria",
        "उमरिया"
      ],
      [
        "Vidisha",
        "विदिशा"
      ]
    ],
    "LEVELS": {
      "vidyalaya": [
        "Class 9",
        "Class 10",
        "Class 11",
        "Class 12",
        "Polytechnic or ITI"
      ],
      "mahavidyalaya": [
        "Undergraduate, 1st year",
        "Undergraduate, 2nd year",
        "Undergraduate, 3rd year",
        "Undergraduate, 4th year",
        "Postgraduate, 1st year",
        "Postgraduate, 2nd year",
        "Research or PhD"
      ]
    },
    "EXAMS": [
      "NEET UG",
      "NEET PG",
      "JEE Main",
      "JEE Advanced",
      "BITSAT",
      "VITEEE",
      "CUET",
      "GATE",
      "CAT",
      "XAT",
      "MAT",
      "CMAT",
      "IPMAT",
      "CLAT",
      "AILET",
      "NDA",
      "CDS",
      "AFCAT",
      "UPSC CSE",
      "MPPSC",
      "SSC CGL",
      "IBPS / SBI PO",
      "IBPS / SBI Clerk",
      "RRB",
      "UGC NET / JRF",
      "CA Foundation",
      "CS",
      "CMA",
      "NIFT",
      "NID",
      "NTSE",
      "ICAR AIEEA",
      "MP PAT",
      "MP PET"
    ],
    "MONTHS": [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec"
    ],
    "S": {
      "title": "Register for the competition",
      "asideOrg": "Shri Krishna Pathey Nyas, Bhopal",
      "asideKicker": "10 August 2026 to 30 September 2026",
      "asideTitle": "Bhagwan Shri Krishna Medhavi Chhatravritti Yojana",
      "slides": [
        {
          "value": "₹1,00,000",
          "label": "Scholarship"
        },
        {
          "value": "102",
          "label": "Scholarships"
        },
        {
          "value": "30",
          "label": "Questions"
        },
        {
          "value": "10",
          "label": "Minutes"
        }
      ],
      "stepLabels": [
        "Mobile number",
        "Applicant details",
        "Education",
        "Declaration"
      ],
      "stepOf": "Step",
      "of": "of",
      "stepTitles": [
        "Enter your mobile number",
        "Applicant details",
        "Education",
        "Declaration and consent"
      ],
      "emailLabel": "Email address",
      "emailInvalid": "Enter a complete email address, for example name@gmail.com",
      "emailTypo": "Did you mean gmail.com?",
      "nameLabel": "Full name",
      "mobileLabel": "Mobile number",
      "mobileHelp": "This number is your identity and will be used to sign in.",
      "mobileInvalid": "Enter a 10-digit number starting with 6, 7, 8 or 9",
      "mobileDuplicate": "This number is already registered. If the account is yours, sign in instead.",
      "dobLabel": "Date of birth",
      "dobPlaceholder": "Select your date of birth",
      "dobModalTitle": "Set birthday",
      "dobConfirm": "Submit",
      "dobCancel": "Close",
      "dobMonth": "Month",
      "dobDay": "Day",
      "dobYear": "Year",
      "dobDayErr": "For the chosen month, day must be 1 to ",
      "dobYearErr": "Year must be between 1900 and 2013",
      "genderLabel": "Gender",
      "genders": [
        "Male",
        "Female",
        "Other"
      ],
      "addressLabel": "Address",
      "cityLabel": "City or village",
      "pinLabel": "PIN code",
      "districtLabel": "District",
      "districtPlaceholder": "Select a district",
      "districtModalTitle": "Select a district",
      "levelPlaceholder": "Select a level",
      "levelModalTitle": "Select your Educational qualification",
      "examLabel": "Competitive exam, preparing or cleared",
      "examPlaceholder": "Select an exam",
      "examModalTitle": "Select a competitive exam",
      "examOther": "Other",
      "examNone": "None",
      "optional": "optional",
      "searchPlaceholder": "Search",
      "noMatch": "No matches found.",
      "submitWorkTitle": "Recording your registration",
      "submitWorkBody": "Please wait, this takes only a moment.",
      "submitDoneTitle": "Registration complete",
      "submitDoneBody": "Taking you to the rules page now.",
      "stateLabel": "State",
      "stateValue": "Madhya Pradesh",
      "categoryLabel": "Applying as, choose one",
      "categories": [
        {
          "name": "Vidyalaya Star",
          "who": "Classes 9 to 12, polytechnic or ITI"
        },
        {
          "name": "Mahavidyalaya Star",
          "who": "College, university"
        }
      ],
      "levelLabel": "Educational qualification",
      "institutionLabel": "Name of school or college currently enrolled in",
      "divyangLabel": "Applying under the Divyang category",
      "divyangNotice": "If selected, a government-issued disability certificate must be produced.",
      "rulesConsent": "I accept the rules of the competition.",
      "rulesLink": "Read the rules",
      "privacyConsent": "I consent to my information being used for this competition, its results and the scholarship process.",
      "privacyLink": "Privacy notice",
      "guardianTitle": "Guardian consent, for candidates under 18",
      "guardianName": "Guardian's name",
      "prev": "Previous step",
      "next": "Continue",
      "finish": "Complete registration",
      "haveAccount": "Already registered?",
      "signIn": "Sign in"
    },
    "markup": {
      "placeholder0": "00000 00000",
      "placeholder1": "name@gmail.com",
      "placeholder2": "000000",
      "text0": "+91",
      "text1": "×",
      "text2": "✓",
      "text3": "×"
    }
  },
  "Rules": {
    "S": {
      "kicker": "Guidelines",
      "title": "Guidelines for the online competition of the Bhagwan Shri Krishna Medhavi Chhatravritti Yojana",
      "chips": [
        "Free entry",
        "30 questions",
        "10 minutes",
        "Two categories"
      ],
      "tocLabel": "Contents",
      "endLabel": "Declaration",
      "declaration": "I have read all the rules and accept them. The information I have provided is correct.",
      "checkboxLabel": "I have read and understood all the rules and I agree to them.",
      "accept": "Accept and continue",
      "back": "Go back",
      "sections": [
        {
          "n": "1",
          "title": "Form of the competition and eligibility",
          "points": [
            "The competition is held in two categories: school level, and college/university level.",
            "School level: students studying in Classes 9 to 12, and trainees of recognised training institutions.",
            "College/university level: students studying in colleges, universities and polytechnics.",
            "Students appearing for higher-education entrance examinations (CAT, JEE, CLAT, NEET) need not be currently enrolled in a school, and may write the name of the school from which they passed Class 12 in the institution column.",
            "The student must be a native resident of Madhya Pradesh studying in Madhya Pradesh, or must have been studying continuously in Madhya Pradesh for five years.",
            "Participation in the competition is free."
          ]
        },
        {
          "n": "2",
          "title": "Information required for the application",
          "points": [
            "Name, address, district, email, mobile number, education and the name of the institution currently attended.",
            "The participant must also choose whether they belong to the school-level category or the college/university-level category.",
            "Fill in all information correctly and on the basis of your own certificates. If false information is found, the entry will be cancelled."
          ]
        },
        {
          "n": "3",
          "title": "Format of the competition",
          "points": [
            "The competition will be based on the philosophy of Maharishi Sandipani, the 14 Vidyas and 64 Kalas of Bhagwan Shri Krishna, his path of public welfare, and the Indian knowledge tradition.",
            "A total of 30 questions will be asked. Only one option will be correct in each question.",
            "Ten minutes are allotted for the competition.",
            "The entry will be submitted automatically when the allotted time is over.",
            "No marks will be deducted for a wrong answer."
          ]
        },
        {
          "n": "4",
          "title": "Selection process",
          "points": [
            "In both the school and college/university categories, separate district-wise lists will first be prepared for the male, female and divyang classes. A combined list of all three will then be prepared, and 50 best students from each of the two categories, that is 100 students in all, will be selected from every district.",
            "The lists received from all districts of the state will be combined and separate state-level lists prepared for the two categories.",
            "Winners will be selected from the state-level list by lottery before the adjudicating board.",
            "The result will be uploaded on the website, and selected students will be informed by email and mobile."
          ]
        },
        {
          "n": "5",
          "title": "Other necessary conditions",
          "points": [
            "After selection, the necessary certificates, marksheet, institutional identity card, proof of residence, Aadhaar and bank account details must be provided.",
            "The right to use the names, districts and institutions of selected students, and the photographs and videos of the event, remains reserved with the organising body.",
            "The right to change the rules and dates relating to the competition, and to cancel all proceedings without assigning any reason, remains reserved with the organising body.",
            "In any dispute the decision of Shri Krishna Pathey Nyas shall be final and binding.",
            "In the event of any judicial dispute the jurisdiction shall be Bhopal."
          ]
        }
      ]
    }
  },
  "SiteFooter": {
    "T": {
      "org": "Shri Krishna Pathey Nyas, Bhopal",
      "dept": "Department of Culture, Government of Madhya Pradesh",
      "address": "Pratham Tal, Ravindra Bhawan Sabhagam, Polytechnic Chauraha, Bhopal, Madhya Pradesh - 462003",
      "linksTitle": "Links",
      "followTitle": "Follow",
      "copyright": "© 2026 Shri Krishna Pathey Nyas, Bhopal",
      "links": [
        {
          "label": "About Us"
        },
        {
          "label": "Pratiyogita"
        },
        {
          "label": "Rules"
        },
        {
          "label": "Contact"
        },
        {
          "label": "Privacy Notice"
        },
        {
          "label": "Terms of Use"
        }
      ]
    },
    "markup": {
      "alt0": "Government of Madhya Pradesh",
      "ariaLabel0": "Instagram",
      "ariaLabel1": "Facebook",
      "ariaLabel2": "X, formerly Twitter",
      "ariaLabel3": "YouTube",
      "text0": "shrikrishnapatheynyas@gmail.com",
      "text1": "0755 4535064"
    }
  },
  "SiteHeader": {
    "NAV": [
      {
        "label": "Home"
      },
      {
        "label": "About Us"
      },
      {
        "label": "Pratiyogita"
      },
      {
        "label": "Rules"
      },
      {
        "label": "My Certificates"
      }
    ],
    "T": {
      "orgShort": "Shri Krishna Pathey Nyas",
      "deptShort": "Department of Culture, Government of MP",
      "menuLabel": "Menu",
      "close": "Close",
      "follow": "Follow",
      "signIn": "Sign in",
      "account": "My account"
    },
    "markup": {
      "alt0": "Government of Madhya Pradesh",
      "alt1": "Shri Krishna Pathey Nyas",
      "ariaLabel0": "Switch language",
      "ariaLabel1": "Instagram",
      "ariaLabel2": "Facebook",
      "ariaLabel3": "X, formerly Twitter",
      "ariaLabel4": "YouTube",
      "text0": "हिं",
      "text1": "EN",
      "text2": "×",
      "text3": "→",
      "text4": "shrikrishnapatheynyas@gmail.com"
    }
  },
  "Shell": {
    "inline": [
      "लोड हो रहा है"
    ]
  }
};
