// Optimises the commissioned vidya/kala plates from design/image/ into public/vk/.
//
// design/image holds 78 plates named "  (1).png" … "  (78).png". They are not the book's own
// figures — they are separately commissioned illustrations, one per entry, numbered in book order:
// the 14 vidyas and then the 64 kalas, which is exactly 78. Plate (3) is captioned SAMAVEDA and
// Samaveda is the third vidya; plate (15) is Krishna with the gopis and Geet is the first kala;
// plate (78) is club-swinging and yoga postures and Vyayamiki is the last. The mapping is 1:1, so
// there is no remainder to place further down an entry — every entry gets exactly one, in its head.
//
// The source PNGs are ~550KB each for a ~755x350 image: lossless encodes of photographic artwork,
// 43MB in total. They are re-encoded to WebP at their native size. **Nothing is resized up** — the
// only resize is a cap on the few that exceed MAX_W, and sharp is told withoutEnlargement anyway.
//
//   node scripts/vk-plates.mjs

import { readdirSync, mkdirSync, writeFileSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "design", "image");
const OUT = join(ROOT, "public", "vk");

/** Wider than any entry column ever renders; the few large plates come down to it, none go up. */
const MAX_W = 1200;
const QUALITY = 82;

const hiSrc = readFileSync(join(ROOT, "lib", "i18n", "hi.ts"), "utf8");
const hi = JSON.parse(hiSrc.slice(hiSrc.indexOf("{"), hiSrc.lastIndexOf("}") + 1));
const order = [...hi.Home_v5.VIDYAS, ...hi.Home_v5.KALAS].map((t) => t[2]);

const plates = new Map();
for (const name of readdirSync(SRC)) {
  const n = name.match(/\((\d+)\)\.png$/i);
  if (n) plates.set(Number(n[1]), name);
}

if (plates.size !== order.length) {
  console.error(`refusing: ${plates.size} plates against ${order.length} entries. The mapping is`
    + ` positional and only holds while those are equal.`);
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });

const manifest = {};
let srcBytes = 0;
let outBytes = 0;

for (const [n, name] of [...plates].sort((a, b) => a[0] - b[0])) {
  const key = order[n - 1];
  const from = join(SRC, name);
  const to = join(OUT, `${key}.webp`);
  srcBytes += statSync(from).size;

  const info = await sharp(from)
    .resize({ width: MAX_W, withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toFile(to);

  outBytes += info.size;
  manifest[key] = { src: `/vk/${key}.webp`, width: info.width, height: info.height, plate: n };
}

writeFileSync(join(ROOT, "vk-plates.json"), `${JSON.stringify({
  $comment: "Entry key -> its plate in public/vk/. Generated by scripts/vk-plates.mjs from"
    + " design/image, which numbers the plates in book order: 14 vidyas then 64 kalas.",
  plates: manifest,
}, null, 2)}\n`);

const mb = (b) => `${(b / 1024 / 1024).toFixed(1)}MB`;
console.log(`${plates.size} plates -> public/vk/`);
console.log(`${mb(srcBytes)} png -> ${mb(outBytes)} webp  (${Math.round((1 - outBytes / srcBytes) * 100)}% smaller)`);
